"""
AnketaMarkdownParser - parses edited Markdown back into FinalAnketa.

Extracts data from the markdown format generated by AnketaGenerator
and merges changes back into the FinalAnketa model.
"""

import re
from typing import List, Optional, Tuple

import structlog

from src.anketa.schema import (
    FinalAnketa, AgentFunction, Integration,
    FAQItem, ObjectionHandler, DialogueExample, FinancialMetric,
    Competitor, MarketInsight, EscalationRule, KPIMetric,
    ChecklistItem, AIRecommendation, TargetAudienceSegment
)

logger = structlog.get_logger()


class AnketaMarkdownParser:
    """Parses Markdown anketa back into FinalAnketa model."""

    def parse(self, content: str, base: FinalAnketa) -> FinalAnketa:
        """
        Parse Markdown v2.0 and merge changes with base anketa.

        Args:
            content: Edited Markdown content
            base: Original FinalAnketa to merge with

        Returns:
            Updated FinalAnketa with changes from Markdown
        """
        logger.info("Parsing markdown anketa v2.0")

        # Start with base data
        data = base.model_dump()

        # Parse basic sections
        data.update(self._parse_company_info(content))
        data.update(self._parse_business_context(content))
        data.update(self._parse_voice_agent(content))
        data.update(self._parse_agent_functions(content))
        data.update(self._parse_integrations(content))

        # Parse v2.0 sections
        data.update(self._parse_faq_items(content))
        data.update(self._parse_objection_handlers(content))
        data.update(self._parse_sample_dialogue(content))
        data.update(self._parse_financial_metrics(content))
        data.update(self._parse_market_analysis(content))
        data.update(self._parse_target_segments(content))
        data.update(self._parse_escalation_rules(content))
        data.update(self._parse_success_kpis(content))
        data.update(self._parse_launch_checklist(content))
        data.update(self._parse_ai_recommendations(content))
        data.update(self._parse_tone_of_voice(content))
        data.update(self._parse_error_handling_scripts(content))
        data.update(self._parse_follow_up_sequence(content))

        # Preserve metadata from base
        data['created_at'] = base.created_at
        data['consultation_duration_seconds'] = base.consultation_duration_seconds
        data['anketa_version'] = base.anketa_version

        logger.info("Markdown v2.0 parsed successfully")
        return FinalAnketa(**data)

    def _parse_company_info(self, content: str) -> dict:
        """Parse company information from table."""
        result = {}

        # Extract table values
        patterns = {
            'company_name': r'\| Компания \| (.+?) \|',
            'industry': r'\| Отрасль \| (.+?) \|',
            'specialization': r'\| Специализация \| (.+?) \|',
            'website': r'\| Сайт \| (.+?) \|',
            'contact_name': r'\| Контактное лицо \| (.+?) \|',
            'contact_role': r'\| Должность \| (.+?) \|',
        }

        for field, pattern in patterns.items():
            match = re.search(pattern, content)
            if match:
                value = match.group(1).strip()
                if value and value != '—':
                    result[field] = value
                elif field in ('website',):
                    result[field] = None
                else:
                    result[field] = ''

        # Parse business description
        desc_match = re.search(
            r'### Описание бизнеса\n\n(.+?)(?=\n###|\n---)',
            content,
            re.DOTALL
        )
        if desc_match:
            desc = desc_match.group(1).strip()
            if desc != '*Не указано*':
                result['business_description'] = desc

        # Parse services list
        result['services'] = self._parse_list_section(content, 'Услуги / Продукты')
        result['client_types'] = self._parse_list_section(content, 'Типы клиентов')

        return result

    def _parse_business_context(self, content: str) -> dict:
        """Parse business context section."""
        return {
            'current_problems': self._parse_list_section(content, 'Текущие проблемы'),
            'business_goals': self._parse_list_section(content, 'Цели автоматизации'),
            'constraints': self._parse_list_section(content, 'Ограничения'),
        }

    def _parse_voice_agent(self, content: str) -> dict:
        """Parse voice agent configuration."""
        result = {}

        # Extract table values
        patterns = {
            'agent_name': r'\| Имя агента \| (.+?) \|',
            'agent_purpose': r'\| Назначение \| (.+?) \|',
            'language': r'\| Язык \| (.+?) \|',
        }

        for field, pattern in patterns.items():
            match = re.search(pattern, content)
            if match:
                value = match.group(1).strip()
                if value and value != '—':
                    result[field] = value

        # Parse voice (format: "female, professional")
        voice_match = re.search(r'\| Голос \| (.+?) \|', content)
        if voice_match:
            voice_str = voice_match.group(1).strip()
            parts = [p.strip() for p in voice_str.split(',')]
            if len(parts) >= 1:
                result['voice_gender'] = parts[0]
            if len(parts) >= 2:
                result['voice_tone'] = parts[1]

        # Parse call direction
        direction_match = re.search(r'\| Тип звонков \| (.+?) \|', content)
        if direction_match:
            direction_str = direction_match.group(1).strip()
            direction_map = {
                'Входящие': 'inbound',
                'Исходящие': 'outbound',
                'Входящие и исходящие': 'both',
            }
            result['call_direction'] = direction_map.get(direction_str, 'inbound')

        # Parse typical questions (FAQ)
        result['typical_questions'] = self._parse_list_section(
            content, 'Типичные вопросы (FAQ)'
        )

        return result

    def _parse_agent_functions(self, content: str) -> dict:
        """Parse agent functions from numbered sections."""
        result = {
            'agent_functions': [],
            'main_function': None,
            'additional_functions': [],
        }

        # Find "Все функции агента" section
        functions_section = re.search(
            r'## 4\. Все функции агента\n\n(.+?)(?=\n---|\Z)',
            content,
            re.DOTALL
        )

        if not functions_section:
            return result

        section_content = functions_section.group(1)

        # Parse each numbered function
        function_pattern = r'### (\d+)\. (.+?)\n\n(.+?)(?=\n### \d+\.|\n\*Приоритет:|$)'
        priority_pattern = r'\*Приоритет: (\w+)\*'

        functions = []
        matches = list(re.finditer(function_pattern, section_content, re.DOTALL))

        for match in matches:
            num = int(match.group(1))
            name = match.group(2).strip()
            description = match.group(3).strip()

            # Find priority after description
            remaining = section_content[match.end():]
            priority_match = re.search(priority_pattern, remaining[:100])
            priority = priority_match.group(1) if priority_match else 'medium'

            # Clean description (remove priority line if present)
            description = re.sub(r'\n\*Приоритет: \w+\*', '', description).strip()

            func = AgentFunction(
                name=name,
                description=description,
                priority=priority
            )
            functions.append((num, func))

        # Sort by number and assign
        functions.sort(key=lambda x: x[0])
        all_functions = [f for _, f in functions]

        result['agent_functions'] = all_functions

        if all_functions:
            result['main_function'] = all_functions[0]
            result['additional_functions'] = all_functions[1:] if len(all_functions) > 1 else []

        return result

    def _parse_integrations(self, content: str) -> dict:
        """Parse integrations from table."""
        integrations = []

        # Find integrations section
        integ_section = re.search(
            r'## 5\. Интеграции\n\n(.+?)(?=\n---|\Z)',
            content,
            re.DOTALL
        )

        if not integ_section:
            return {'integrations': integrations}

        section_content = integ_section.group(1)

        # Check if no integrations
        if 'не требуются' in section_content.lower():
            return {'integrations': integrations}

        # Parse table rows
        row_pattern = r'\| (.+?) \| (.+?) \| (Да|Нет) \|'
        for match in re.finditer(row_pattern, section_content):
            name = match.group(1).strip()
            purpose = match.group(2).strip()
            required = match.group(3).strip() == 'Да'

            # Skip header row
            if name in ('Система', '------'):
                continue

            integrations.append(Integration(
                name=name,
                purpose=purpose,
                required=required
            ))

        return {'integrations': integrations}

    def _parse_list_section(self, content: str, section_name: str) -> List[str]:
        """Parse a bulleted list section."""
        # Find section
        pattern = rf'### {re.escape(section_name)}\n\n(.+?)(?=\n###|\n---|\n## )'
        match = re.search(pattern, content, re.DOTALL)

        if not match:
            return []

        section_content = match.group(1).strip()

        if section_content == '*Не указано*':
            return []

        # Parse bullet points
        items = []
        for line in section_content.split('\n'):
            line = line.strip()
            if line.startswith('- '):
                item = line[2:].strip()
                if item:
                    items.append(item)

        return items

    # =========================================================================
    # V2.0 PARSING METHODS
    # =========================================================================

    def _parse_faq_items(self, content: str) -> dict:
        """Parse FAQ items with answers."""
        items = []

        section = self._extract_section(content, r'## 6\. FAQ с ответами')
        if not section or 'не сгенерирован' in section.lower():
            return {'faq_items': items}

        # Pattern: ### N. Question [category]
        pattern = r'### \d+\. (.+?)(?:\s*\[(\w+)\])?\n\n> (.+?)(?=\n### \d+\.|\Z)'
        for match in re.finditer(pattern, section, re.DOTALL):
            question = match.group(1).strip()
            category = match.group(2) or 'general'
            answer = match.group(3).strip()

            items.append(FAQItem(
                question=question,
                answer=answer,
                category=category
            ))

        return {'faq_items': items}

    def _parse_objection_handlers(self, content: str) -> dict:
        """Parse objection handling scripts."""
        handlers = []

        section = self._extract_section(content, r'## 7\. Работа с возражениями')
        if not section or 'не проработаны' in section.lower():
            return {'objection_handlers': handlers}

        # Pattern: ### N. «Objection»
        pattern = r'### \d+\. [«"](.+?)[»"]\n\n\*\*Ответ:\*\* (.+?)(?:\n\n\*\*Далее:\*\* (.+?))?(?=\n### \d+\.|\Z)'
        for match in re.finditer(pattern, section, re.DOTALL):
            objection = match.group(1).strip()
            response = match.group(2).strip()
            follow_up = match.group(3).strip() if match.group(3) else None

            handlers.append(ObjectionHandler(
                objection=objection,
                response=response,
                follow_up=follow_up
            ))

        return {'objection_handlers': handlers}

    def _parse_sample_dialogue(self, content: str) -> dict:
        """Parse sample dialogue."""
        dialogue = []

        section = self._extract_section(content, r'## 8\. Пример диалога')
        if not section or 'не сгенерирован' in section.lower():
            return {'sample_dialogue': dialogue}

        # Pattern: **Role:** Message *(intent)*
        pattern = r'\*\*(.+?):\*\* (.+?)(?:\s*\*\((.+?)\)\*)?(?=\n\n\*\*|\Z)'
        for match in re.finditer(pattern, section, re.DOTALL):
            role_str = match.group(1).strip()
            message = match.group(2).strip()
            intent = match.group(3).strip() if match.group(3) else None

            # Map role labels
            role = 'bot' if 'Агент' in role_str else 'client'

            dialogue.append(DialogueExample(
                role=role,
                message=message,
                intent=intent
            ))

        return {'sample_dialogue': dialogue}

    def _parse_financial_metrics(self, content: str) -> dict:
        """Parse financial metrics from table."""
        metrics = []

        section = self._extract_section(content, r'## 9\. Финансовая модель')
        if not section or 'не указаны' in section.lower():
            return {'financial_metrics': metrics}

        # Parse table: | Метрика | Значение | Источник | Примечание |
        pattern = r'\| (.+?) \| (.+?) \| (.+?) \| (.+?) \|'
        for match in re.finditer(pattern, section):
            name = match.group(1).strip()
            value = match.group(2).strip()
            source_label = match.group(3).strip()
            note = match.group(4).strip()

            if name in ('Метрика', '-------'):
                continue

            # Map source labels back
            source_map = {
                'Клиент': 'client',
                'AI-бенчмарк': 'ai_benchmark',
                'Расчёт': 'calculated'
            }
            source = source_map.get(source_label, 'ai_benchmark')

            metrics.append(FinancialMetric(
                name=name,
                value=value,
                source=source,
                note=note if note != '—' else None
            ))

        return {'financial_metrics': metrics}

    def _parse_market_analysis(self, content: str) -> dict:
        """Parse market analysis section."""
        result = {
            'competitors': [],
            'market_insights': [],
            'competitive_advantages': []
        }

        section = self._extract_section(content, r'## 10\. Анализ рынка')
        if not section:
            return result

        # Parse competitors
        competitors_section = re.search(
            r'### Конкуренты\n\n(.+?)(?=\n### |\Z)',
            section, re.DOTALL
        )
        if competitors_section and 'не определены' not in competitors_section.group(1).lower():
            comp_content = competitors_section.group(1)
            # Parse each competitor: #### Name
            comp_pattern = r'#### (.+?)\n(?:\*Цены: (.+?)\*\n)?\n(.+?)(?=\n#### |\n### |\Z)'
            for match in re.finditer(comp_pattern, comp_content, re.DOTALL):
                name = match.group(1).strip()
                price_range = match.group(2).strip() if match.group(2) else None
                details = match.group(3)

                strengths = []
                weaknesses = []
                for line in details.split('\n'):
                    if '✅' in line:
                        strengths.append(line.split('✅')[-1].strip())
                    elif '❌' in line:
                        weaknesses.append(line.split('❌')[-1].strip())

                result['competitors'].append(Competitor(
                    name=name,
                    strengths=strengths,
                    weaknesses=weaknesses,
                    price_range=price_range
                ))

        # Parse market insights
        insights_section = re.search(
            r'### Рыночные инсайты\n\n(.+?)(?=\n### |\Z)',
            section, re.DOTALL
        )
        if insights_section and 'не сгенерированы' not in insights_section.group(1).lower():
            for line in insights_section.group(1).split('\n'):
                if line.startswith('- '):
                    insight_text = line[2:].strip()
                    # Remove emoji
                    for emoji in ['🔥', '📊', '📝']:
                        insight_text = insight_text.replace(emoji, '').strip()

                    relevance = 'high' if '🔥' in line else ('medium' if '📊' in line else 'low')
                    result['market_insights'].append(MarketInsight(
                        insight=insight_text,
                        relevance=relevance
                    ))

        # Parse competitive advantages
        advantages_section = re.search(
            r'### Конкурентные преимущества клиента\n\n(.+?)(?=\n---|\n## |\Z)',
            section, re.DOTALL
        )
        if advantages_section:
            result['competitive_advantages'] = self._parse_bullets(advantages_section.group(1))

        return result

    def _parse_target_segments(self, content: str) -> dict:
        """Parse target audience segments."""
        segments = []

        section = self._extract_section(content, r'## 11\. Целевые сегменты')
        if not section or 'не определены' in section.lower():
            return {'target_segments': segments}

        # Pattern: ### N. Segment Name
        pattern = r'### \d+\. (.+?)\n\n(.+?)(?=\n### \d+\.|\Z)'
        for match in re.finditer(pattern, section, re.DOTALL):
            name = match.group(1).strip()
            details = match.group(2)

            # Extract description (first paragraph before **Болевые точки**)
            desc_match = re.match(r'(.+?)(?=\n\n\*\*Болевые|\Z)', details, re.DOTALL)
            description = desc_match.group(1).strip() if desc_match else ''

            # Parse pain points and triggers
            pain_points = []
            triggers = []
            for line in details.split('\n'):
                if '😓' in line:
                    pain_points.append(line.split('😓')[-1].strip())
                elif '⚡' in line:
                    triggers.append(line.split('⚡')[-1].strip())

            segments.append(TargetAudienceSegment(
                name=name,
                description=description,
                pain_points=pain_points,
                triggers=triggers
            ))

        return {'target_segments': segments}

    def _parse_escalation_rules(self, content: str) -> dict:
        """Parse escalation rules from table."""
        rules = []

        section = self._extract_section(content, r'## 12\. Правила эскалации')
        if not section or 'не определены' in section.lower():
            return {'escalation_rules': rules}

        # Parse table rows
        pattern = r'\| (.+?) \| (.+?) \| (.+?) \|'
        for match in re.finditer(pattern, section):
            trigger = match.group(1).strip()
            urgency_label = match.group(2).strip()
            action = match.group(3).strip()

            if trigger in ('Триггер', '-------'):
                continue

            # Map urgency labels
            urgency = 'medium'
            if '🚨' in urgency_label or 'Немедленно' in urgency_label:
                urgency = 'immediate'
            elif '⏰' in urgency_label or 'час' in urgency_label:
                urgency = 'hour'
            elif '📅' in urgency_label or 'дня' in urgency_label:
                urgency = 'day'

            rules.append(EscalationRule(
                trigger=trigger,
                urgency=urgency,
                action=action
            ))

        return {'escalation_rules': rules}

    def _parse_success_kpis(self, content: str) -> dict:
        """Parse success KPIs from table."""
        kpis = []

        section = self._extract_section(content, r'## 13\. KPI и метрики успеха')
        if not section or 'не определены' in section.lower():
            return {'success_kpis': kpis}

        # Parse table: | KPI | Цель | Бенчмарк | Измерение |
        pattern = r'\| (.+?) \| (.+?) \| (.+?) \| (.+?) \|'
        for match in re.finditer(pattern, section):
            name = match.group(1).strip()
            target = match.group(2).strip()
            benchmark = match.group(3).strip()
            measurement = match.group(4).strip()

            if name in ('KPI', '----'):
                continue

            kpis.append(KPIMetric(
                name=name,
                target=target,
                benchmark=benchmark if benchmark != '—' else None,
                measurement=measurement if measurement != '—' else None
            ))

        return {'success_kpis': kpis}

    def _parse_launch_checklist(self, content: str) -> dict:
        """Parse launch checklist."""
        checklist = []

        section = self._extract_section(content, r'## 14\. Чеклист запуска')
        if not section or 'не определён' in section.lower():
            return {'launch_checklist': checklist}

        # Pattern: - ☐/○ Item — Responsible **(обязательно)**
        for line in section.split('\n'):
            if not line.strip().startswith('- '):
                continue

            required = '☐' in line or '**(обязательно)**' in line
            text = line[2:].strip()

            # Remove checkbox symbols
            text = text.replace('☐', '').replace('○', '').strip()

            # Extract responsible
            responsible = 'client'
            if '👤 Клиент' in text:
                responsible = 'client'
            elif '👥 Команда' in text:
                responsible = 'team'
            elif '🤝 Совместно' in text:
                responsible = 'both'

            # Clean item text
            item_text = re.sub(r'\s*—\s*(👤 Клиент|👥 Команда|🤝 Совместно).*', '', text).strip()

            if item_text:
                checklist.append(ChecklistItem(
                    item=item_text,
                    required=required,
                    responsible=responsible
                ))

        return {'launch_checklist': checklist}

    def _parse_ai_recommendations(self, content: str) -> dict:
        """Parse AI recommendations."""
        recommendations = []

        section = self._extract_section(content, r'## 15\. Рекомендации AI-эксперта')
        if not section or 'не сгенерированы' in section.lower():
            return {'ai_recommendations': recommendations}

        # Pattern: ### N. Priority Recommendation
        pattern = r'### \d+\. (?:🔴|🟡|🟢)?\s*(.+?)\n\n\*\*Ожидаемый эффект:\*\* (.+?)\n\n\*Приоритет: (\w+) \| Затраты: (\w+)\*'
        for match in re.finditer(pattern, section, re.DOTALL):
            recommendation = match.group(1).strip()
            impact = match.group(2).strip()
            priority = match.group(3).strip()
            effort_label = match.group(4).strip()

            # Map effort labels
            effort_map = {'Низкие': 'low', 'Средние': 'medium', 'Высокие': 'high'}
            effort = effort_map.get(effort_label, 'medium')

            recommendations.append(AIRecommendation(
                recommendation=recommendation,
                impact=impact,
                priority=priority,
                effort=effort
            ))

        return {'ai_recommendations': recommendations}

    def _parse_tone_of_voice(self, content: str) -> dict:
        """Parse tone of voice guidelines."""
        tone = {}

        section = self._extract_section(content, r'## 16\. Тон коммуникации')
        if not section or 'не определён' in section.lower():
            return {'tone_of_voice': tone}

        # Parse Do section
        do_match = re.search(r'### ✅ Делать\n\n(.+?)(?=\n### |$)', section, re.DOTALL)
        if do_match:
            tone['do'] = do_match.group(1).strip()

        # Parse Don't section
        dont_match = re.search(r'### ❌ Не делать\n\n(.+?)(?=\n### |\n---|\Z)', section, re.DOTALL)
        if dont_match:
            tone['dont'] = dont_match.group(1).strip()

        return {'tone_of_voice': tone}

    def _parse_error_handling_scripts(self, content: str) -> dict:
        """Parse error handling scripts."""
        scripts = {}

        section = self._extract_section(content, r'## 17\. Скрипты обработки ошибок')
        if not section or 'не определены' in section.lower():
            return {'error_handling_scripts': scripts}

        # Parse each script block
        label_map = {
            '🤔 Не понял запрос': 'not_understood',
            '⚠️ Техническая проблема': 'technical_issue',
            '🚫 Вне компетенции': 'out_of_scope'
        }

        for label, key in label_map.items():
            pattern = rf'\*\*{re.escape(label)}:\*\*\n> [«"](.+?)[»"]'
            match = re.search(pattern, section)
            if match:
                scripts[key] = match.group(1).strip()

        return {'error_handling_scripts': scripts}

    def _parse_follow_up_sequence(self, content: str) -> dict:
        """Parse follow-up sequence."""
        section = self._extract_section(content, r'## 18\. Последовательность follow-up')
        if not section:
            return {'follow_up_sequence': []}

        return {'follow_up_sequence': self._parse_bullets(section)}

    # =========================================================================
    # HELPER METHODS
    # =========================================================================

    def _extract_section(self, content: str, header_pattern: str) -> Optional[str]:
        """Extract section content by header pattern."""
        pattern = rf'{header_pattern}\n\n(.+?)(?=\n---|\n## |\Z)'
        match = re.search(pattern, content, re.DOTALL)
        return match.group(1).strip() if match else None

    def _parse_bullets(self, text: str) -> List[str]:
        """Parse bullet points from text."""
        items = []
        for line in text.split('\n'):
            line = line.strip()
            if line.startswith('- '):
                item = line[2:].strip()
                # Clean emoji prefixes
                for emoji in ['😓', '⚡', '✅', '❌', '🔥', '📊', '📝', '☐', '○']:
                    item = item.replace(emoji, '').strip()
                if item and item != '*Не указано*':
                    items.append(item)
        return items


def parse_anketa_markdown(content: str, base: FinalAnketa) -> FinalAnketa:
    """
    Convenience function to parse markdown into anketa.

    Args:
        content: Markdown content
        base: Base anketa to merge with

    Returns:
        Updated FinalAnketa
    """
    parser = AnketaMarkdownParser()
    return parser.parse(content, base)
